name: Run linters

on:
  push:
    branches:
      - main
    # Don't run on translation updates
    paths-ignore:
     - 'app/src/lang/translations/*.yaml'
  pull_request:
    branches:
      - main
    # Don't run on translation updates
    paths-ignore:
     - 'app/src/lang/translations/*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint
